//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentProduct
    {
        public System.Guid Id_CommentProduct { get; set; }
        public System.Guid Id_Товара { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
    
        public virtual Товары Товары { get; set; }
    }
}
