//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentCashier
    {
        public System.Guid Id_CommentCashier { get; set; }
        public System.Guid Id_Кассира { get; set; }
        public string Nickname { get; set; }
        public string Comment { get; set; }
    
        public virtual Кассир Кассир { get; set; }
    }
}
