//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceipt
    {
        public System.Guid Id_Чека { get; set; }
        public string Товар { get; set; }
        public int Количество { get; set; }
        public long Цена_за_единицу_товара { get; set; }
        public Nullable<long> Общая_цена { get; set; }
    }
}
