//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Чек_Покупки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Чек_Покупки()
        {
            this.Товары_куплены = new HashSet<Товары_куплены>();
        }
    
        public System.Guid Id_Чека { get; set; }
        public System.DateTime Дата_и_время_покупки { get; set; }
        public System.Guid Id_Кассира { get; set; }
        public Nullable<System.Guid> Номер_Дисконтной_карты { get; set; }
        public System.Guid Код_оплаты { get; set; }
        public System.Guid Id_Кассы { get; set; }
    
        public virtual C__Кассы C__Кассы { get; set; }
        public virtual Вид_оплаты Вид_оплаты { get; set; }
        public virtual Дисконтная_карта Дисконтная_карта { get; set; }
        public virtual Кассир Кассир { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товары_куплены> Товары_куплены { get; set; }
    }
}
